---
title: "R Notebook"
output: html_notebook
---

## Plans/further development

Example concentrating part of the values in a point

Finish Lemma for building counterexamples

Data averaged posterior
  - Convex combinations
  - Transforms do not change

Non-monotonous, finish.

Can the lemma to create counterexamples for non-monotonous functions be used to prove that you need infinite test functions?

Test-function orthogonality.

## Inverse transforms

$$
\forall y \in Y,  \tilde\theta \in \Theta, x \in [0, 1] : r_{\phi, g}(x | \tilde\theta, y) = 1 - r_{\phi, f}(1 - x | \tilde\theta, y) \\
\forall y \in Y,  \tilde\theta \in \Theta, i \in \{0, \dots, M \} :  R_{\phi, g}(i | \tilde\theta, y) = 1 - R_{\phi, f}(M - i - 1 | \tilde\theta, y) 
$$

$$
N^g_\text{equals} = N^f_\text{equals}\\
N^g_\text{less} = M - N^f_\text{less} - N^f_\text{equals}\\

R_{\phi,g}(i | \tilde\theta, y) = \mathbb{P} \left(N^g_{\mathtt{less}} + K \leq i \right) =
  \mathbb{P} \left(M - N^f_\text{less} - N^f_\text{equals} + K \leq i \right) = \\
  \mathbb{P} \left(N^f_{\mathtt{less}} + N^f_\text{equals} - K \geq  M  -i \right) = \\
  1 - \mathbb{P} \left(N^f_{\mathtt{less}} + K <   M - i \right) = \\
  1 - \mathbb{P} \left(N^f_{\mathtt{less}} + K \leq   M - i - 1 \right) = 
  1 - R_{\phi,f}(M - i - 1 | \tilde\theta, y)
$$


$$
Q_{\phi,g}(i | y) = \int_\Theta \mathrm{d}\tilde\theta \: \pi_\text{post}(\tilde\theta|y)  R_{\phi,g}( i| \tilde\theta, y) = \\
\int_\Theta \mathrm{d}\tilde\theta \: \pi_\text{post}(\tilde\theta|y) - \int_\Theta \mathrm{d}\tilde\theta \: \pi_\text{post}(\tilde\theta|y) R_{\phi,f}(M - i - 1| \tilde\theta, y) = \\
1 - Q_{\phi,f}(M - i - 1|y)
$$

$$
\int_Y \mathrm{d}y\: Q_{\phi,g}(i | y) \pi_\text{marg}(y) = 
\int_Y \mathrm{d}y\: \pi_\text{marg}(y) - \int_Y \mathrm{d}y\: Q_{\phi,f}(M - i - 1 | y) \pi_\text{marg}(y) = \\
1 - \int_Y \mathrm{d}y\: Q_{\phi,f}(M - i - 1 | y)
$$
Reverse implication SBC

$$
\int_Y \mathrm{d}y\: Q_{\phi,g}(i | y) \pi_\text{marg}(y) = 
1 - \frac{M - i}{M + 1} = \frac{i + 1}{M + 1}
$$
Forward implication:

$$
\int_Y \mathrm{d}y\: Q_{\phi,f}(M - i - 1 | y) =  1 - \int_Y \mathrm{d}y\: Q_{\phi,g}(i | y) \pi_\text{marg}(y) = 1 - \frac{i + 1}{M + 1} = \frac{(M - i - 1) + 1}{M + 1}
$$

Continuous case

$$
r_{\phi,f}(x | \tilde\theta, y) = 
\mathbb{P}\left(C_{\phi,f} \left(f \left(\tilde\theta, y \right) | y \right) - e D_{\phi,f} \left(f \left(\tilde\theta, y \right) | y \right) \leq x\right) 
$$

$$
C_{\phi,g}\left( s | y\right)=\int_{\Theta}\mathrm{d}\theta\mathbb{\,I}\left[g\left(\theta, y \right) \leq s\right]\phi(\theta | y) = 
\int_{\Theta}\mathrm{d}\theta\mathbb{\,I}\left[-f\left(\theta, y \right) \leq s\right]\phi(\theta | y) = \\
\int_{\Theta}\mathrm{d}\theta\mathbb{\,I}\left[f\left(\theta, y \right) \geq -s\right]\phi(\theta | y) = 1 - C_{\phi,f}(-s | y) + D_{\phi,f}(-s|y) \\
D_{\phi,g}(s|y) = D_{\phi,f}(-s|y)
$$

$$
r_{\phi, g}(x | \tilde\theta, y) = \mathbb{P}\left(C_{\phi,g} \left(g \left(\tilde\theta, y \right) | y \right) - e D_{\phi,g} \left(g \left(\tilde\theta, y \right) | y \right) \leq x\right) = \\
\mathbb{P}\left(C_{\phi,g} \left(-f \left(\tilde\theta, y \right) | y \right) - e D_{\phi,g} \left(-f \left(\tilde\theta, y \right) | y \right) \leq x\right) =  \\
\mathbb{P}\left(1 - C_{\phi,f} \left(f \left(\tilde\theta, y \right) | y \right) + (1 - e) D_{\phi,f} \left(f \left(\tilde\theta, y \right) | y \right) \leq x\right) = \\
\mathbb{P}\left( C_{\phi,f} \left(f \left(\tilde\theta, y \right) | y \right) - (1 - e) D_{\phi,f} \left(f \left(\tilde\theta, y \right) | y \right) \geq  1 - x\right) = \\
1 - \mathbb{P}\left( C_{\phi,f} \left(f \left(\tilde\theta, y \right) | y \right) - e D_{\phi,f} \left(f \left(\tilde\theta, y \right) | y \right) \leq  1 - x\right) = \\
1 - r_{\phi, f}(1 -x | \tilde\theta, y)
$$
Where the second-to-last identity holds, because the probability of exact equality is $0$ and $1 - e$ has the same distribution as $e$.

$$
q_{\phi,g}(x|y) = 
\int_\Theta \mathrm{d} \tilde\theta \: \pi_\text{post}(\tilde\theta | y) r_{\phi,g}(x | \tilde\theta, y) = \int_\Theta \mathrm{d} \tilde\theta \: \pi_\text{post}(\tilde\theta | y) - \int_\Theta \mathrm{d} \tilde\theta \: \pi_\text{post}(\tilde\theta | y) r_{\phi,f}(1 - x | \tilde\theta, y) =
1 - q_{\phi,f}(1 - x | y)
$$

$$
\int_Y \mathrm{d}y \: q_{\phi,g}(x|y) \pi_\text{marg}(y) = \int_Y \mathrm{d}y \:  \pi_\text{marg}(y) - \int_Y \mathrm{d}y \: q_{\phi,f}(1 - x|y) \pi_\text{marg}(y) = \\
1 -  \int_Y \mathrm{d}y \: q_{\phi,f}(1 - x|y) \pi_\text{marg}(y)
$$

## Data-averaged posterior

$$
\forall \theta \in \Theta: \pi_\text{prior}(\theta) = \int_Y \mathrm{d} y \int_\Theta \mathrm{d}\tilde\theta  \: \pi_\text{post}(\theta |y) \pi_\text{obs}(y | \tilde\theta) \pi_\text{prior}(\tilde \theta)
$$

$$
\forall{s}: \int_\Theta \mathrm{d}\theta \: \mathbb{I}\left[ f(\theta) < s \right] \pi_\text{prior}(\theta) = 
\int_\Theta \mathrm{d}\tilde\theta \int_Y \mathrm{d} y \int_\Theta \mathrm{d}\theta \: \mathbb{I}\left[f(\theta) < s\right] \phi(\theta, y) \pi_\text{obs}(y|\tilde\theta) \pi_\text{prior}(\tilde\theta)
$$

In some discussions, SBC is linked to the concept of data-averaged posterior. It is true that data-averaged posterior equals the prior:

\begin{equation}
\pi(\theta) = \int_Y \mathrm{d} y \int_\Theta \mathrm{d}\tilde\theta  \: \pi(\theta |y) \pi(y | \tilde\theta) \pi(\tilde \theta) \label{eq:data_averaged_posterior}
\end{equation}

\begin{definition}[Data-averaged posterior] A posterior family $\phi$ satisfies the data-averaged posterior criterion for a function $f: \Theta \to \mathbb{R}$ if

\begin{equation*}
\forall{s}: \int_\Theta \mathrm{d}\theta \: \mathbb{I}\left[ f(\theta) < s \right] \pi(\theta) = 
\int_\Theta \mathrm{d}\tilde\theta \int_Y \mathrm{d} y \int_\Theta \mathrm{d}\theta \: \mathbb{I}\left[f(\theta) < s\right] \phi(y, \theta) \pi(y|\tilde\theta) \pi(\tilde\theta)
\end{equation*}

\end{definition}

It however turns out that $\phi$ satisfying this relationship, i.e.

\begin{equation}
\pi(\theta) = \int \int \mathrm{d}\tilde{y} \mathrm{d}\tilde\theta \: \phi(\tilde{y},\theta) \pi(\tilde{y} | \tilde\theta) \pi(\tilde \theta) \label{eq:data_averaged_posterior_phi}
\end{equation}

Is not a sufficient condition to pass continuous SBC. A quick counter-example: we have a very simple model:

\begin{align}
\theta &\sim \mathrm{Unif}(0,1) \notag\\
y  &\sim \mathrm{Bernoulli}(\theta) \label{eq:bernoulli_model}
\end{align}

We know the correct solution is 

\begin{align}
    \pi(\theta | 0) = \mathrm{Beta}(\theta | 1, 2) = 2(1-\theta) \notag\\
    \pi(\theta | 1) = \mathrm{Beta}(\theta | 2, 1) = 2\theta \label{eq:bernoulli_correct}
\end{align}

However, flipping the $y$ values, i.e. having:
\begin{align}
    \phi(0, \theta) = \mathrm{Beta}(\theta | 2, 1) \notag\\
    \phi(1, \theta) = \mathrm{Beta}(\theta | 1, 2) \label{eq:bernoulli_flipped}
\end{align}

(and really any two functions that average to 1 over the whole $[0, 1]$ interval) Will satisfy \ref{eq:data_averaged_posterior_phi}.
We can however show that the posterior family from \ref{eq:bernoulli_flipped} will not pass SBC. (I currently only did a quick simulation to check, but it should be easy to also show mathematically).



## Value of Q



## Non-monotonous functions - simple case

### Lemma 1

Take $\phi$, $f,g: Y \times \Theta \to \mathbb{R}, h: \mathbb{R} \to \mathbb{R}$ such that $\forall y \in Y, \theta \in \mathbb{R}: g(\theta, y) = h(f(\theta, y)$.  Disjoint intervals $[a_1, b_1], [a_2,b_2], [a_3, b_3] \subset \mathbb{R}, a_1 < b_1 < a_2 < b_2 < a_3 < b_3$ such that

$$
\forall x_1 \in [a_1, b_1], x_2 \in [a_2,b_2], x_3 \in [a_3, b_3]: h(x_1) \leq h(x_2),  h(x_3) \leq h(x_2)
$$

$\phi$ passes SBC for $f$.

Disjoint $Y_1, Y_2 \subset Y, Y_3 = Y \setminus  (Y_1 \cup Y_2)$

$$
q_{\phi,f}(x | y) = \begin{cases}
x & \text{for } y \in Y_3 \\
x & \text{for } y \in Y_1 \cup Y_2, C_{\phi,f}(C^{}) \\
> x & \text{for } y \in Y_1, C_f(C^{-1}_{\phi,f}(a_2 | y) | y) < x < C_f(C^{-1}_{\phi,f}(b_2 | y) | y) \\
> x & \text{for } y \in Y_2, C_f(C^{-1}_{\phi,f}(a_3 | y) | y) < x < C_f(C^{-1}_{\phi,f}(b_3 | y) | y) \\
< x & \text{for } y \in Y_1, C_f(C^{-1}_{\phi,f}(a_3 | y) | y) < x < C_f(C^{-1}_{\phi,f}(b_3 | y) | y) \\
< x & \text{for } y \in Y_2, C_f(C^{-1}_{\phi,f}(a_2 | y) | y) < x < C_f(C^{-1}_{\phi,f}(b_2 | y) | y)
\end{cases}
$$

$$
\forall y_1 \in Y_1, y_2 \in Y_2: \\
C_f(a_2 | y_1) < C_f(a_2 | y_2) \\
C_f(b_2 | y_1) < C_f(b_2 | y_2) \\
C_f(a_3 | y_1) < C_f(a_3 | y_2) \\
C_f(b_3 | y_1) < C_f(b_3 | y_2)
$$

Now $\phi$ does not pass SBC for $g$.


(we can prove the other non-monotonous ordering by using $-h$, which maintains SBC)

### Lemma 2

Take $\Theta = \mathbb{R}$ and $\text{id} : Y \times \mathbb R \to \mathbb{R}, \text{id}(y, \theta) = \theta$   $C_\text{id}(s|y)$ is invertible over the domain of $f$ for all $y$. Take any continuous, almost everywhere smooth bijection $u: [0,1] \to [0,1], u(0) = 0, u(1) = 1$ and disjoint $Y_1, Y_2 \subset Y$ (with non-zero mass).

$$
a,b \in [0,1]\\
\frac{a}{b} = \frac{\int_{y \in Y_2} \mathrm{d}y \: \pi_\text{marg}(y)}{\int_{y \in Y_1} \mathrm{d}y \: \pi_\text{marg}(y)}
$$

$$
v(x) = a u(x) + (1-a)x\\
w(x) = b (2x - u(x)) + (1-b)x\\

t_1(\theta, y) =  C^{-1}_\text{id}(v(C_\text{id}(\theta|y)) | y)\\
t_2(\theta, y) =  C^{-1}_\text{id}(w(C_\text{id}(\theta|y)) | y)
$$

$$
C^{-1}_\text{id}(v_i(C_\text{id}(\theta|y)) | y) = x \\
v_i(C_\text{id}(\theta|y)) = C_\text{id}(x |y) \\
C_\text{id}(\theta|y) = v^{-1}(C_\text{id}(x |y)) \\
\theta = C^{-1}_\text{id}(v^{-1}(C_\text{id}(x |y)) | y) \\
$$

$t_{1,2}$ are invertible and we can define:

TODO: Omega and w are similar visually, change

$$
\omega(\theta|y) = \begin{cases}
  \pi_\text{post}(t^{-1}_1(\theta,y)|y) \frac{\partial t^{-1}_1}{\partial \theta}(\theta, y) | y) & \text{if } y \in Y_1 \\
  \pi_\text{post}(t^{-1}_2(\theta,y)|y) \frac{\partial t^{-1}_2}{\partial \theta}(\theta, y) | y) & \text{if } y \in Y_2 \\
  \pi_\text{post}(\theta | y) & \text{otherwise}
\end{cases}
$$

now $\omega$ satisfies SBC for $\text{id}$.


$$
y \in Y_1: C_{\omega,\text{id}}(s|y) = \int_{\Theta}\mathrm{d}\theta\mathbb{\,I}\left[\theta \leq s\right]\omega\left(\theta | y\right) = \\
\int_{\Theta}\mathrm{d}\theta\mathbb{\,I}\left[\theta \leq s\right]\pi_\text{post}(t^{-1}_1(\theta,y)|y) \frac{\partial t^{-1}_1}{\partial \theta}(\theta, y) | y) = \\
= \int_{\Theta}\mathrm{d}\bar\theta\mathbb{\,I}\left[t_1(\theta,y) \leq s\right]\pi_\text{post}(\bar\theta,y) = C_{t_1}(s|y) \\


$$

$$
y \in Y_1: q_{\omega,\text{id}}(x | y) = C_\text{id} \left(C^{-1}_{\omega,\text{id}}(x | y) | y \right) =
  C_\text{id} \left(C^{-1}_{t_1}(x | y) | y \right) =
  \int \mathrm{d}\theta \: \mathbb{I}\left[\theta< C^{-1}_{t_1}(x | y)\right]\pi_\text{post}(\theta|y) = \\
  = \int \mathrm{d}\theta \: \mathbb{I}\left[C_{t_1}(\theta |y)< x\right]\pi_\text{post}(\theta|y) = \\
  = \int \mathrm{d}\theta \: \mathbb{I}\left[\int \mathrm{d}\tilde\theta\: \mathbb{I}\left[t_1(\tilde\theta, y) < \theta \right] \pi_\text{post}(\tilde\theta|y) < x\right]\pi_\text{post}(\theta|y) = \\
  = \int \mathrm{d}\theta \: \mathbb{I}\left[\int \mathrm{d}\tilde\theta\: \mathbb{I}\left[\tilde\theta < t_1^{-1}(\theta, y) \right] \pi_\text{post}(\tilde\theta|y) < x\right]\pi_\text{post}(\theta|y) = \\
  = \int \mathrm{d}\theta \: \mathbb{I}\left[C_\text{id}(t_1^{-1}(\theta, y)|y) < x\right]\pi_\text{post}(\theta|y) = \\
  = \int \mathrm{d}\theta \: \mathbb{I}\left[\theta < t_1(C^{-1}_\text{id}(x|y)\right]\pi_\text{post}(\theta|y) = \\
  = C_\text{id}\left(t_1(C_\text{id}^{-1}(x|y), y) \right) = v(x)

$$

Analogously

$$
y \in Y_2: q_{\omega,\text{id}}(x | y)  = w(x)
$$
So we have

$$
\int_Y \mathrm{d}y \: q_{\omega,\text{id}}(x | y) \pi_\text{marg}(y) = \\
\int_{Y_1} \mathrm{d}y \: q_{\omega,\text{id}}(x | y) \pi_\text{marg}(y) + \int_{Y_2} \mathrm{d}y \: q_{\omega,\text{id}}(x | y) \pi_\text{marg}(y) + \int_{Y \setminus Y_1 \cup Y_2} \mathrm{d}y \: q_{\omega,\text{id}}(x | y) \pi_\text{marg}(y) = \\
v(x) \int_{Y_1} \mathrm{d}y \: \pi_\text{marg}(y) + w(x)\int_{Y_2} \mathrm{d}y\pi_\text{marg}(y) + x \int_{Y \setminus Y_1 \cup Y_2} \mathrm{d}y \: \pi_\text{marg}(y) = \\
(a u(x) + (1-a)x)\int_{Y_1} \mathrm{d}y \: \pi_\text{marg}(y) + (b (2x - u(x)) + (1-b)x)\int_{Y_2} \mathrm{d}y\pi_\text{marg}(y) + x \int_{Y \setminus Y_1 \cup Y_2} \mathrm{d}y \: \pi_\text{marg}(y) =\\
u(x) a \int_{Y_1} \mathrm{d}y \: \pi_\text{marg}(y) + b(2x - u(x)) \int_{Y_2} \mathrm{d}y\pi_\text{marg}(y) + x \left( \int_{Y \setminus Y_1 \cup Y_2} \mathrm{d}y \: \pi_\text{marg}(y) + (1-a)\int_{Y_1} \mathrm{d}y \: \pi_\text{marg}(y) + (1-b)\int_{Y_2} \mathrm{d}y\pi_\text{marg}(y)\right) \\
$$

We note that from requirements on $a,b$ we have $a \int_{Y_1} \mathrm{d}y \: \pi_\text{marg}(y) = b \int_{Y_2} \mathrm{d}y \: \pi_\text{marg}(y)$ and $u(x) + u^{-1}(x)$ se we have

$$
\int_Y \mathrm{d}y \: q_{\omega,\text{id}}(x | y) \pi_\text{marg}(y) = \\
\left(u(x) + 2x - u(x)\right)\left( a \int_{Y_1} \mathrm{d}y \: \pi_\text{marg}(y)\right) + x \left(1 - 2a \int_{Y_1} \mathrm{d}y \: \pi_\text{marg}(y) \right) = x \\

$$

$$
u(x) + v(x) = 2x \\
v(x) = 2x - u(x)
$$



## Bernoulli example

$$
q_{\phi,f}(x | 0) + q_{\phi,f}(x | 1) = x \\
C_f(C^{-1}_{\phi,f}(x | 0) | 0) + C_f(C^{-1}_{\phi,f}(x | 1) | 1) = x
$$

Correct solution

$$
\begin{align}
    \pi_\text{post}(\theta | 0) = \mathrm{Beta}(\theta | 1, 2) = 2(1-\theta) \notag\\
    \pi_\text{post}(\theta | 1) = \mathrm{Beta}(\theta | 2, 1) = 2\theta
\end{align}
$$

### Projection

$f_1$ - identity function (assuming $0 \leq s \leq 1$)

$$
C_{f_1}(s | 0) = \int_0^s \mathrm{d}\theta \: 2(1 - \theta)  =  2s - s^2 \\
C_{f_1}(s | 1) = \int_0^s \mathrm{d}\theta \: 2\theta = s^2 \\
$$

$$
\forall x \in [0,1]: 
  \Phi^{-1}(x | 1) = \sqrt{2x - 2\Phi^{-1}(x | 0) + (\Phi^{-1}(x | 0))^2} \\
$$



The corresponding data-averaged posterior criterium for the identity function (and thus also the whole posterior) simply entails:

$$
\forall \theta \in [0,1]: \phi(\theta, 0) + \phi(\theta, 1) = 2
$$
DAP entails

$$
\Phi(s| 0) + \Phi(s | 1) = 2s \\
\Phi(s| 1)  = 2s - \Phi(s | 0) \\
s = \Phi^{-1}(2s - \Phi(s | 0) | 1) \\
$$

subst $x = 2s - \Phi(s | 0)$


$$
\Phi^{-1}(x | 1) = \sqrt{2x - 2\Phi^{-1}(x | 0) + (\Phi^{-1}(x | 0))^2} \\
\Phi^{-1}(2s - \Phi(s | 0) | 1) = \sqrt{2(2s - \Phi(s | 0)) - 2\Phi^{-1}(2s - \Phi(s | 0) | 0) + (\Phi^{-1}(2s - \Phi(s | 0) | 0))^2} \\
s = \sqrt{2(2s - \Phi(s | 0)) - 2\Phi^{-1}(2s - \Phi(s | 0) | 0) + (\Phi^{-1}(2s - \Phi(s | 0) | 0))^2} \\
$$

$$
x^2 = 4x  - 2f(x) - 2f^{-1}(2x - f(x)) + (f^{-1}(2x - f(x)))^2 \\
$$

Substituting $x = \Phi(s|1)$ into the SBC condition

$$
s = \sqrt{2\Phi(s | 1) - 2\Phi^{-1}(\Phi(s | 1) | 0) + (\Phi^{-1}(\Phi(s | 1) | 0))^2} \\
s^2 = 2\Phi(s | 1) - 2\Phi^{-1}(\Phi(s | 1) | 0) + (\Phi^{-1}(\Phi(s | 1) | 0))^2 \\
\Phi^{-1}(\Phi(s | 1) | 0) = 1 - \sqrt{1 - 2 \Phi(s|1) + s^2} \\
\Phi(s | 1) = \Phi(1 - \sqrt{1 - 2 \Phi(s|1) + s^2}| 0)
$$

$$
2s-\Phi(s | 0) = \Phi(1 - \sqrt{1 - 2 (2s-\Phi(s | 0)) + s^2}| 0) \\
2x - F(x) = F(1 - \sqrt{1 - 4x + 2 F(x) + x^2}) \\
F(x) = 2x - F(1 - \sqrt{1 - 4x + 2 F(x) + x^2}) \\
$$

Since derivative has to be between 0 and 2, we get at least $f^\prime(x) < 2 - x$ (see Mathematica NTB)

Choosing $\Phi(s|1)$ this implies a valid inverse CDF as long as:

$$
$$

$$
\Phi^{-1}(x | 0) = \begin{cases}
   \frac{2}{3}x & x < \frac{3}{4} \\
   \frac{1}{2} + 2(x - \frac{3}{4}) & x \geq \frac{3}{4} \\
\end{cases} \\
\Phi^{-1}(x | 1) = \begin{cases}
   \frac{1}{3}\sqrt{6x + 4 x^2} & x < \frac{3}{4} \\
   \sqrt{3 - 6x + 4 x ^2} & x \geq \frac{3}{4} \\
\end{cases}
$$
$$
\phi(\theta | 0) = \begin{cases}
 \frac{3}{2} & \theta \leq \frac{1}{2} \\
 \frac{1}{2} & \theta > \frac{1}{2}
\end{cases}\\
\phi(\theta | 1) = \begin{cases}
 \frac{3s}{\sqrt{1 + 4 s ^ 2}} & \theta \leq \frac{\sqrt{3}}{2} \\
 \frac{s}{\sqrt{4s ^2  - 3}} & \theta > \frac{\sqrt{3}}{2}
\end{cases}
$$



### Likelihood

$$
C_{f_1}(s | 0) = \int_0^1 \mathrm{d}\theta \: \mathbb{I}[1 - \theta < s]2(1 - \theta)  =  
  2 \int_{1-s}^1 \mathrm{d}\theta \: (1 - \theta) = 1 - 2s + s^2 \\
C_{f_2}(s | 1) = C_{f_1}(s | 1) = \int_0^s \mathrm{d}\theta \: 2\theta = s^2 \\
C^{-1}_{\phi,f_2}(x | 1) = C^{-1}_{\phi,f_1}(x | 1) =  \Phi^{-1}(x | 1) \\
C_{\phi,f_2}(s | 0) = \int_0^1 \mathrm{d}\theta \: \mathbb{I}[1 - \theta < s]\phi(\theta, 0) = \int_{1-s}^1 \mathrm{d}\theta \: \phi(\theta,0) = 1 - \Phi(\theta | 0) \\
C^{-1}_{\phi,f_2}(x | 0) = \Phi^{-1}(1 - x | 0) 
$$

$$
\forall x \in [0,1]: \frac{1}{2} - \Phi^{-1}(1 - x | 0) + \frac{(\Phi^{-1}(1 - x| 0))^2}{2} + \frac{(\Phi^{-1}(x | 1))^2}{2}  = x 
$$

### Swap

$$
f_3(y, \theta) = \begin{cases}\theta&  \text{for } \theta < \frac{1}{2} \\ \theta - 1,&  \text{otherwise} \end{cases}
$$

(assuming $-\frac{1}{2} \leq s \leq \frac{1}{2}$)

$$
C_{f_3}(s | 0) = \int_0^1 \mathrm{d}\theta \: \mathbb{I}\left[f_3(\theta) \leq s\right] (2 - 2\theta) =
\begin{cases}
 \int_{\frac{1}{2}}^{s + 1} \mathrm{d}\theta \: (2 - 2\theta)  & -\frac{1}{2} < s < 0 \\
 \int_{\frac{1}{2}}^{1} \mathrm{d}\theta (2 - 2\theta) + \int_{0}^{s} \mathrm{d}\theta (2 - 2\theta) & 0 \leq s < \frac{1}{2}
\end{cases} = \\
= \begin{cases}
 \frac{1}{4} - s^2& -\frac{1}{2} < s < 0 \\
 \frac{1}{4} + 2 s - s^2  & 0 \leq s < \frac{1}{2}
\end{cases}
\\
C_{f_3}(s | 1) =
\begin{cases}
 \int_{\frac{1}{2}}^{s + 1} \mathrm{d}\theta \: 2\theta  & -\frac{1}{2} < s < 0 \\
 \int_{\frac{1}{2}}^{1} \mathrm{d}\theta \: 2\theta + \int_{0}^{s} \mathrm{d}\theta \: 2\theta & 0 \leq s < \frac{1}{2}
\end{cases}
= \begin{cases}
 \frac{3}{4} + 2s + s^2& -\frac{1}{2} < s < 0 \\
 \frac{3}{4} + s^2  & 0 \leq s < \frac{1}{2}
\end{cases}
$$

$$
h_y = \Phi \left(\frac{1}{2} | y\right) \\
C_{\phi,f_3}(s | y) =
\begin{cases}
 \int_{\frac{1}{2}}^{s + 1} \mathrm{d}\theta \: \phi(\theta, y)  & -\frac{1}{2} < s < 0 \\
 \int_{\frac{1}{2}}^{1} \mathrm{d}\theta \: \phi(\theta, y) + \int_{0}^{s} \mathrm{d}\theta \: \phi(\theta, y) & 0 \leq s < \frac{1}{2}
\end{cases}  = \\
= \begin{cases}
  \Phi(s + 1| y) - h_y & \text{for } -\frac{1}{2} <s < 0 \\
1 -   h_y + \Phi(s | y)& 0 \leq s < \frac{1}{2}
\end{cases}
$$
Solving for the inverse:

$$
z = \begin{cases}
  \Phi(s + 1| y) - h_y & \text{for } s < 0 \\
1 -   h_y + \Phi(s | y)& \text{otherwise}
\end{cases} \\


z_1 = \Phi(s + 1| y) - h_y\\
z_1 + h_y = \Phi(s + 1| y)\\
\Phi^{-1}(z_1 + h_y | y) - 1 = s \text{ for } z < 1 - h_y \\

z_2 = 1 -   h_y + \Phi(s | y)\\
z_2 - 1 + h_y =  \Phi(s | y)\\
\Phi^{-1}(z_2 - 1 + h_y) = s \text{ for } z \geq 1 - h_y \\
$$
$$
C^{-1}_{\phi,f_3}(x | y) = \begin{cases}
\Phi^{-1}(x + h_y | y) - 1  & \text{ for } x < 1 - h_y \\
\Phi^{-1}(x - 1 + h_y |y) & \text{ otherwise }
\end{cases}
$$

$$
q_{\phi,f_3}(x | 0) = \begin{cases}
  \frac{1}{4} - \left(\Phi^{-1}(x + h_0 | 0) - 1 \right)^2 & \text{for }  x < 1 - h_0 \\
  \frac{1}{4} - \left( \Phi^{-1}(x - 1 + h_0 | 0) - 1\right)^2 + 1  & \text{ otherwise }
\end{cases}
\\
q_{\phi,f_3}(x | 1) = \begin{cases}
  -\frac{1}{4} + \left(\Phi^{-1}(x + h_1 | 1)\right)^2 & \text{for }  x < 1 - h_1 \\
  \frac{3}{4} + \left( \Phi^{-1}(x - 1 + h_1|1)\right)^2  & \text{ otherwise }
\end{cases}
$$

So the SBC condition $x = \frac{1}{2}(q_{\phi,f_3}(x | 0) + q_{\phi,f_3}(x | 1))$ resolves to four cases. First, when $x \leq \min\{1 - h_0, 1 - h_1\}$:

$$
2x = - \left(\Phi^{-1}(x + h_0 | 0) - 1 \right)^2 + \left(\Phi^{-1}(x + h_1 | 1)\right)^2  \\
\Phi^{-1}(x + h_1 | 1) = \sqrt{\left(\Phi^{-1}(x + h_0 | 0) - 1 \right)^2 + 2x}
$$

Second, when $1 - h_0 \leq x \leq 1 - h_1$

$$
2x =  - \left( \Phi^{-1}(x - 1 + h_0 | 0) - 1\right)^2 + 1 + \left(\Phi^{-1}(x + h_1 | 1)\right)^2 \\
\Phi^{-1}(x + h_1 | 1) = \sqrt{\left( \Phi^{-1}(x - 1 + h_0 | 0) - 1\right)^2 + 2x - 1}
$$
Third, when $1 - h_1 \leq x \leq 1 - h_0$

$$
2x = -\left(\Phi^{-1}(x + h_0 | 0) - 1\right)^2 + 1 + \left( \Phi^{-1}(x - 1 + h_1|1)\right)^2 \\
\Phi^{-1}(x - 1 + h_1|1) = \sqrt{\left(\Phi^{-1}(x + h_0 | 0) - 1\right)^2 + 2x - 1}
$$

And lastly, when $x \geq \max\{1 - h_0, 1 - h_1\}$

$$
2x = 1 - \left( \Phi^{-1}(x - 1 + h_0 | 0) - 1\right)^2 + 1 + \left( \Phi^{-1}(x - 1 + h_1|1)\right)^2 \\
\Phi^{-1}(x - 1 + h_1|1) = \sqrt{\left( \Phi^{-1}(x - 1 + h_0 | 0) - 1\right)^2 + 2x - 2} 
$$

Substituting $\bar{h} = h_1 - h_0$ and $y = x + \bar{h} + h_0$ in the first two cases and $y = x - 1 + \bar{h} + h_0$ into the other cases as needed we obtain: 

$$
0 < y -h_1 + h_0 < 1 \\
h_1 - h_0 < y  < 1 + h_1 - h_0
$$

$$
\Phi^{-1}(y | 1) = 
  \begin{cases}
    \sqrt{\left(\Phi^{-1}(y - \bar{h}  | 0) - 1 \right)^2 + 2(y - \bar{h} - h_0)}
    & \text{for } \bar{h} < y \leq 1 + \bar{h} \\
    \sqrt{\left( \Phi^{-1}(y - 1 -\bar{h} | 0) - 1\right)^2 + 2(y -  \bar{h} - h_0) - 1}
    & \text{for } 1 + \bar{h} \leq y  \\
    \sqrt{\left(\Phi^{-1}(y + 1 - \bar{h} | 0) - 1\right)^2 + 2(y -  \bar{h} - h_0) + 1}
    & \text{for } y  \leq \bar{h} \\
    \sqrt{\left( \Phi^{-1}(y - \bar{h} | 0) - 1\right)^2  + 2y - 2\bar{h} +  2h_0} 
    & \text{for } \bar{h} < y < 1 + \bar{h} \\
  \end{cases}
$$
After the substitution, we notice that the 1st and 4th branches are identical, so we end up with:

$$
\Phi^{-1}(y | 1) = 
  \begin{cases}
    \sqrt{\left(\Phi^{-1}(y - \bar{h}  | 0) - 1 \right)^2 + 2(y - \bar{h} - h_0)}
    & \text{for } \bar{h} < y \leq 1 + \bar{h} \\
    \sqrt{\left( \Phi^{-1}(y - 1 -\bar{h} | 0) - 1\right)^2 + 2(y -  \bar{h} - h_0) - 1}
    & \text{for } 1 + \bar{h} \leq y  \\
    \sqrt{\left(\Phi^{-1}(y + 1 - \bar{h} | 0) - 1\right)^2 + 2(y -  \bar{h} - h_0) + 1}
    & \text{for } y  \leq \bar{h} 
  \end{cases}
$$




Since we need to ensure $\Phi^{-1}(0 | 1) = 0$ we obtain:

$$
\begin{cases}
    0 = \left(\Phi^{-1}(1 - h_1 + h_0 | 0) - 1\right)^2  - 2h_1 + 1
    & \text{for } h_0 \leq h_1 \\
    0 = \left(\Phi^{-1}(h_0 - h_1  | 0) - 1 \right)^2 -2h_1
    & \text{for } h_0 > h_1
  \end{cases}
$$

Since $\Phi^{-1}$ is bounded within $[0,1]$ the above implies $h_0 \leq h_1 \iff  \frac{1}{2} \leq h_1$
and we can rearrange as:

$$
h_0 \leq h_1 \iff  \frac{1}{2} \leq h_1 \\
\begin{cases}
    \Phi^{-1}(1 - h_1 + h_0 | 0) =  1 - \sqrt{2h_1 - 1}
    & \text{for } h_0 \leq h_1 \\
    \Phi^{-1}(h_0 - h_1  | 0) = 1 - \sqrt{2h_1}
    & \text{for } h_0 > h_1
  \end{cases}
$$

$$
h_0 \leq h_1 \implies (1 - h_1 + h_0 > h_0 \iff  1 - \sqrt{2h_1 - 1} > \frac{1}{2}) \\

$$

So to construct a posterior family satisfying SBC w.r.t. $f_3$, we can choose almost any $\Phi^{-1}(x | 0)$, calculate $h_0$, then use Equation~\ref{TODO} to determine $h_1$ and finally compute $\Phi^{-1}(x | 1)$ via Equation~\ref{TODO}.

Now we can show that this is indeed a different condition than the one in Example~\ref{TODO}. Let us take $\phi_B$ from Example~\ref{TODO} - as discussed there, it passes SBC w.r.t $f_1$: 

$$
\begin{gather*}
\Phi^{-1}_B(x | 0) = \begin{cases}
   \frac{2}{3}x & x < \frac{3}{4} \\
   \frac{1}{2} + 2(x - \frac{3}{4}) & x \geq \frac{3}{4} \\
\end{cases} \\
\Phi^{-1}_B(x | 1) = \begin{cases}
   \frac{1}{3}\sqrt{6x + 4 x^2} & x < \frac{3}{4} \\
   \sqrt{3 - 6x + 4 x ^2} & x \geq \frac{3}{4} \\
\end{cases}    
\end{gather*}
$$
In this case we obtain $h_0 = \frac{3}{4} > \frac{3}{4}(\sqrt{2} - 1) = h_1$ while 

$$
\Phi^{-1}_B(h_0 - h_1 | 0) =  \Phi^{-1}_B \left(\frac{3}{4}(2 - \sqrt{2}) | 0\right) = \frac{1}{2}(2 - \sqrt{2}) = 1 - \frac{1}{\sqrt{2}} \\
1 - \sqrt{2h_1} = 1 - \sqrt{\frac{3}{2}(\sqrt{2} - 1)} = 1 - \frac{\sqrt{3(\sqrt{2} - 1)}}{\sqrt{2}} 
$$
so the condition in Equation~\ref{TODO} does not hold and $\phi_B$ cannot pass SBC w.r.t $f_3$.


### Ties - continuous

$$
f_4(\theta, y) = \begin{cases}
\theta & \theta < \frac{1}{2} \\
\frac{1}{2} & \theta \geq \frac{1}{2} 
\end{cases}
$$
$$
C_{f_4}(s | 0) = \begin{cases}
   \int_0^s \mathrm{d}\theta \: 2(1 - \theta)  =  2s - s^2  & s < \frac{1}{2}\\
   1 & s \geq \frac{1}{2}
\end{cases}\\
D_{f_4}(s | 0) = \begin{cases}
    0 & s < \frac{1}{2}\\
   \int_{\frac{1}{2}}^1 \mathrm{d}\theta \: 2(1 - \theta)  =  \frac{1}{4} & s \geq \frac{1}{2}
\end{cases}\\
C_{f_4}(s | 1) = \begin{cases}
  \int_0^s \mathrm{d}\theta \: 2\theta = s^2 & s < \frac{1}{2}\\
  1 & s \geq \frac{1}{2}
\end{cases} \\
D_{f_4}(s | 1) = \begin{cases}
    0 & s < \frac{1}{2}\\
   \int_{\frac{1}{2}}^1 \mathrm{d}\theta \: 2\theta  =  \frac{3}{4} & s \geq \frac{1}{2}
\end{cases}
$$
We'll reuse the notation $h_y = \Phi \left(\frac{1}{2}|y \right)$

$$
C^{-1}_{\phi, f_4}(x | y) = \begin{cases}
   \Phi^{-1}(x | y) & x < h_y \\
   \frac{1}{2} & x \geq h_y
\end{cases}\\
D_{\phi, f_4}(s | y) = \begin{cases}
  \int_{\frac{1}{2}}^1 \mathrm{d}\theta \: \phi (\theta | y) = 1 - h_y & s = \frac{1}{2} \\
  0 & s \neq \frac{1}{2}
\end{cases}
$$

Using Lemma~\ref{le:value_of_q}

$$
q_{\phi,f_4}(x | y) = \begin{cases}
  C_{f_4}(\Phi^{-1}(x | y) | y)  & x < h_y \\
  C_{f_4}\left(\frac{1}{2}| y \right) + \frac{D_{f_4}\left(\frac{1}{2}| y \right)}{D_{\phi,f_4}\left(\frac{1}{2}| y \right)} \left(x - C_{\phi,f_4}\left(\frac{1}{2}|y \right) \right)& x \geq h_y
\end{cases} = \\
= \begin{cases}
  C_{f_4}(\Phi^{-1}(x | y) | y)  & x < h_y \\
  1 + \frac{D_{f_4}\left(\frac{1}{2}| y \right)}{1 - h_y} \left(x - 1 \right)& x \geq h_y
\end{cases}
$$

$$
q_{\phi,f_4}(x | 0) = \begin{cases}
1 - \left(\Phi^{-1}(x | 0) - 1\right)^2 & x < h_0 \\
1 + \frac{x - 1}{4(1 - h_0)} & x \geq h_0
\end{cases} \\

q_{\phi,f_4}(x | 1) = \begin{cases}
\left(\Phi^{-1}(x | 1)\right)^2 & x < h_1 \\
1 + \frac{3(x - 1)}{4(1 - h_1)} & x \geq h_1
\end{cases}
$$

$$
2x = \begin{cases}
  - \left(\Phi^{-1}(x | 0) - 1\right)^2 + \left(\Phi^{-1}(x | 1)\right)^2 + 1 & x< \min\{h_0, h_1\} \\
  - \left(\Phi^{-1}(x | 0) - 1\right)^2 + 2 + \frac{3(x - 1)}{4(1 - h_1)}& h_1 \leq x < h_0 \\
 1 + \frac{x - 1}{4(1 - h_0)} + \left(\Phi^{-1}(x | 1)\right)^2 & h_0 \leq x < h_1 \\
 2 + \frac{x - 1}{4(1 - h_0)} + \frac{3(x - 1)}{4(1 - h_1)} & \max\{h_0, h_1\} \leq x
\end{cases}
$$

If $\max\{h_0, h_1\} = 1$ SBC fails (TODO) if not, then the last condition implies

$$
h_1 = \frac{20 h_0 - 4}{32 h_0 - 7}
$$

Substituting this into the second branch in \ref{TODO} we obtain a set of constraints on $\Phi^{-1}$:

$$
\begin{align*}
x< \min\{h_0, h_1\} & \implies \Phi^{-1}(x | 1) = \sqrt{2x + (\Phi^{-1}(x | 0) - 1)^2 - 1} \\
h_1 \leq x < h_0 & \implies \Phi^{-1}(x | 0) = 1 - \frac{1}{2}\sqrt{\frac{x - 1}{4  h_0 - 1}} \\
h_0 \leq x < h_1 & \implies \Phi^{-1}(x | 1) = \frac{1}{2}\sqrt{\frac{(32 h_0 - 7)x - 16 h_0 + 3}{4 h_0 - 1}}
\end{align*}
$$
Let's take $\Phi^{-1}(x | 0) = x^2, \Phi^{-1}(x | 1) = \sqrt{2x - 2x^2 + x^4}$. This will pass SBC w.r.t $f_1$. However, it will not pass SBC w.r.t $f_4$ for multiple reasons. Probably the easiest to see is that unless $h_0 = h_1$, some part of at least one of the inverse CDF functions is required to be a shifted and scaled square-root of $x$, which neither can satisfy. And indeed $\sqrt{\frac{1}{2}} = h_0 \neq h_1 \approx 0.15$. Also the relation between $h_0$ and $h_1$ from \ref{TODO} is violated.


### Ties - discrete

$$
q_{\phi,f_1}(x | 0) = \begin{cases}
   \frac{2x}{3 \phi\left(\frac{1}{3}|0\right)} & x \leq \phi\left(\frac{1}{3}|0\right) \\
   \frac{2}{3} + \frac{x - \phi\left(\frac{1}{3}|0\right)}{3\left(1 - \phi\left(\frac{1}{3}|0\right)\right)} & \text{otherwise}
\end{cases} \\
q_{\phi,f_1}(x | 1) = \begin{cases}
   \frac{x}{3 \phi\left(\frac{1}{3}|1\right)} & x \leq \phi\left(\frac{1}{3}|1\right) \\
   \frac{1}{3} + \frac{2\left(x - \phi\left(\frac{1}{3}|0\right)\right)}{3\left(1 - \phi\left(\frac{1}{3}|0\right)\right)} & \text{otherwise}
\end{cases}
$$
