---
title: "Sims for general math"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(cowplot)
theme_set(cowplot::theme_cowplot())
```


```{r}
plot_q <- function(pfunc, qfunc, ensure_vals, ..., p_args = list(), q_args = list()) {
  pfunc_wrap <- function(x) {
    do.call(pfunc, c(list(x), list(...), p_args))
  }
  qfunc_wrap <- function(p) {
    do.call(qfunc, c(list(p), list(...), q_args))
  }
  
  x_base <- pfunc_wrap(ensure_vals)
  df <- data.frame(x = c(seq(0,1, length.out = 200), x_base - 1e-5, x_base, x_base + 1e-5)) %>%
    filter(x >= 0, x <= 1) %>%
    mutate(q = pfunc_wrap(qfunc_wrap(x))) 
  
  df <- rbind(data.frame(x = 0, q = 0),
              df,
              data.frame(x = 1, q = 1))
  
  df %>%
    ggplot(aes(x,q)) +
      geom_abline(intercept = 0, slope = 1, color = "blue") +
      geom_line()
}

plot_q(ppois, qpois, ensure_vals = 0:15,  lambda = 3)

plot_q(pfunc = pbinom, qfunc = qbinom, ensure_vals = 0:10,  size = 10, prob = 0.4)

```

```{r}
# z ~ rnorm(), y = if_else(z <= 0, 0, z)
prelunormal <- function(q) {
  case_when(q < 0 ~ 0,
            q == 0 ~ 0.5,
            q > 0 ~ pnorm(q))
}

qrelunormal <- function(x) {
  case_when(x <= 0.5 ~ 0,
            x > 0.5 ~ qnorm(x))
}

plot_q(pfunc = prelunormal, qfunc = qrelunormal, ensure_vals = 0:10)
```

```{r}
plot_q(pfunc = ppois, qfunc = qrelunormal, ensure_vals = 0:30, p_args = list(lambda = 3))
plot_q(pfunc =prelunormal, qfunc = qpois, ensure_vals = -5:5, q_args = list(lambda = 3))
```


```{r}
plot_q_D <- function(test_dist, true_dist, ensure_vals, ..., test_args = list(), true_args = list()) {
  dist_test_q <- function(x) { 
    qfunc <- get(paste0("q", test_dist))
    do.call(qfunc, c(list(x), list(...), test_args))
  }
  dist_true_q <- function(x) { 
    qfunc <- get(paste0("q", true_dist))
    do.call(qfunc, c(list(x), list(...), true_args))
  }
  
  dist_test_d <- function(x) { 
    dfunc <- get(paste0("d", test_dist))
    do.call(dfunc, c(list(x), list(...), test_args))
  }
  dist_true_d <- function(x) { 
    dfunc <- get(paste0("d", true_dist))
    do.call(dfunc, c(list(x), list(...), true_args))
  }
  
  dist_test_p <- function(x) { 
    pfunc <- get(paste0("p", test_dist))
    do.call(pfunc, c(list(x), list(...), test_args))
  }
  dist_true_p <- function(x) { 
    pfunc <- get(paste0("p", true_dist))
    do.call(pfunc, c(list(x), list(...), true_args))
  }
    
    
  x_base <- unique(dist_test_p(ensure_vals), dist_true_p(ensure_vals))
  df <- data.frame(x = c(seq(0,1, length.out = 200), x_base - 1e-5, x_base, x_base + 1e-5)) %>%
    filter(x >= 0, x <= 1) %>%
    mutate(s = dist_test_q(x),
           #q = dist_true_p(s) - dist_true_d(s) + if_else(dist_test_d(s) > 0, (dist_true_d(s)/dist_test_d(s)) * (x - dist_test_p(s)) , 0) ) %>%
           q = dist_true_p(s) + if_else(dist_test_d(s) > 0, (dist_true_d(s)/dist_test_d(s)) * (x - dist_test_p(s)) , 0) ) %>%
    select(-s)
  
  df <- rbind(data.frame(x = 0, q = 0),
              df,
              data.frame(x = 1, q = 1))
  
  df_points <- df %>% filter(x %in% x_base)
  
  df %>%
    ggplot(aes(x,q)) +
      geom_abline(intercept = 0, slope = 1, color = "blue") +
      geom_line() +
      geom_point(data = df_points, color = "orangered")
}
```

```{r}
plot_q(pbinom, qbinom, ensure_vals = 0:10, size = 10, prob = 0.4)
plot_q_D("binom", "binom", ensure_vals = 0:10, size = 10, prob = 0.4)

```


```{r}
plot_q(pbinom, qbinom, ensure_vals = 0:10, size = 10, p_args = list(prob = 0.4), q_args = list(prob = 0.35))
plot_q_D("binom", "binom", ensure_vals = 0:10, size = 10, test_args = list(prob = 0.3), true_args = list(prob = 0.4))
```


```{r}
plot_q_D("binom", "pois", ensure_vals = 0:10, test_args = list(size = 10, prob = 0.4), true_args = list(lambda = 4))
```

```{r}
sim_phi_solution <- function(first_x, first_val, N_iters) {
  res_x <- numeric(N_iters)
  res_val <- numeric(N_iters)
  cur_x <- first_x
  cur_val <- first_val
  for(i in 1:N_iters) {
    res_x[i] <- cur_x
    res_val[i] <- cur_val
    new_x <- 1 - sqrt(1 - 4*cur_x + 2 * cur_val + cur_x ^ 2)
    cur_val <- 2 * cur_x - cur_val
    cur_x <- new_x
  }
  data.frame(x = res_x, val = res_val, dir = "fwd")
}

# sim_phi_solution_back <- function(first_x, first_val, N_iters) {
#   res_x <- numeric(N_iters)
#   res_val <- numeric(N_iters)
#   cur_x <- first_x
#   cur_val <- first_val
#   for(i in 1:N_iters) {
#     res_x[i] <- cur_x
#     res_val[i] <- cur_val
#     prop_val <- 0.5 * (-1 - cur_val + 4*cur_x)
#     new_x <- 2 - sqrt(4 - 2*prop_val - 2* cur_x + cur_x^2)
#     cur_val <- 2 * cur_x - prop_val
#     cur_x <- new_x
#   }
#   data.frame(x = res_x, val = res_val, dir = "rev")
# }

correct_post <- data.frame(x = seq(0,1, length.out = 200)) %>% mutate(val = 2*x-x^2)

plot_solution <- function(sol) {
  if(length(unique(sol$x) > 3)) {
    quad_geom <- geom_smooth(formula = y ~ x + I(x^2), method = "lm", color = "gray", fullrange = TRUE)
  } else {
    quad_geom <- NULL
  }
  sol %>%
  ggplot(aes(x = x, y = val)) + 
    geom_hline(yintercept = 0, color = "blue") +
    geom_hline(yintercept = 1, color = "blue") +
    geom_vline(xintercept = 0, color = "blue") +
    geom_vline(xintercept = 1, color = "blue") +
    geom_line(data = correct_post, color = "orangered", linetype = "dashed") +
    geom_abline(slope = 1, intercept = 0, color = "green", linetype = "dashed") +
    quad_geom +
    #geom_line() +
    geom_point()
}

```
```{r}
#first_x <- 0.9; first_val <- 2*0.9 - 0.9^2 + 0.009;
#first_x <- 0.95; mix <- 0.9; first_val <- mix * first_x + (1 - mix)*(2*first_x - first_x^2);
#first_val <- 0.3; mix <- 1; first_x <- 2 - mix * sqrt(4 - 2 *first_val) - (1 - mix) * sqrt(3 - 2*first_val)
first_x <- 1/4; first_val <- 1/10;
#sol <- sim_phi_solution(0.5, 2*0.5 - 0.5^2, 5000)
#sol <- sim_phi_solution(0.9, 2*0.9 - 0.9^2, 5000)
sol <- sim_phi_solution(first_x,first_val, 5000)
sol
# sol_back <- sim_phi_solution_back(first_x,first_val, 5000)
# sol_back

# rbind(sol, sol_back) %>%
plot_solution(sol)
```

