---
title: "Non-monotonous transformations"
output: html_notebook
---

```{r}

```


```{r}

sample_from_density <- function(dens, max_dens, N_samples = 100) {
  res <- rep(NA_real_, length.out = N_samples)
  rejected <- rep(TRUE, length.out = N_samples)
  repeat {
    N_rejected <- sum(rejected)
    proposals <- runif(N_rejected)
    checks <- runif(N_rejected)
    res[rejected] <- proposals
    d_proposals <- dens(proposals)
    if(any(d_proposals > max_dens)) {
      stop("Density above max_dens")
    }
    rejected[rejected] <- checks * max_dens * dunif(proposals) >= d_proposals
    if(!any(rejected)) {
      break
    }
  }
  res
}

my_backend_density <- function(dens0, dens1, max_dens) {
  structure(list(dens0 = dens0, dens1 = dens1, max_dens = max_dens), class = "my_backend_density")
}




SBC_fit.my_backend_density <- function(backend, generated, cores) {
  if(generated$y == 0) {
    posterior::draws_matrix(theta = sample_from_density(backend$dens0, backend$max_dens))
  } else if (generated$y == 1) {
    posterior::draws_matrix(theta = sample_from_density(backend$dens1, backend$max_dens))
  } else {
    stop("Invalid")
  }
}

SBC_backend_iid_draws.my_backend_func <- function(backend) {
  TRUE
}

my_backend_func_invcdf <- function(tfunc0, tfunc1) {
  structure(list(tfunc0 = tfunc0, tfunc1 = tfunc1), class = "my_backend_func_invcdf")
}

SBC_fit.my_backend_func_invcdf <- function(backend, generated, cores) {
  if(generated$y == 0) {
    posterior::draws_matrix(theta = backend$tfunc0(runif(N_samples_simple_gq)))
  } else if (generated$y == 1) {
    posterior::draws_matrix(theta = backend$tfunc1(runif(N_samples_simple_gq)))
  } else {
    stop("Invalid")
  }
}

SBC_backend_iid_draws.my_backend_func_invcdf <- function(backend) {
  TRUE
}


my_globals <- c("SBC_fit.my_backend_func", "SBC_backend_iid_draws.my_backend_func", "SBC_fit.my_backend_func_invcdf",
                "SBC_backend_iid_draws.my_backend_func_invcdf", "N_samples_simple_gq")

```

